#YamlMime:PythonReference
api_name: []
items:
- _type: class
  children: []
  class: azure.servicefabric.models.ValidationFailedChaosEvent
  fullName: azure.servicefabric.models.ValidationFailedChaosEvent
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: msrest.serialization.Model
    type: azure.servicefabric.models.chaos_event.ChaosEvent
  langs:
  - python
  module: azure.servicefabric.models
  name: ValidationFailedChaosEvent
  source:
    id: ValidationFailedChaosEvent
    path: \azure_servicefabric-5.6.130-py3.5.egg\azure\servicefabric\models\validation_failed_chaos_event.py
    remote:
      branch: master
      path: \azure_servicefabric-5.6.130-py3.5.egg\azure\servicefabric\models\validation_failed_chaos_event.py
      repo: https://github.com/swatDong/azure-sdk-for-python
    startLine: 15
  summary: 'Bases: `azure.servicefabric.models.chaos_event.ChaosEvent`

    Chaos event corresponding to a failure during validation.'
  syntax:
    content: ValidationFailedChaosEvent(self, time_stamp_utc, reason=None)
    parameters:
    - description: ''
      id: time_stamp_utc
      type:
      - datetime
    - description: Polymorphic Discriminator
      id: Kind
      type:
      - str
    - description: ''
      id: reason
      type:
      - str
  type: Class
  uid: azure.servicefabric.models.ValidationFailedChaosEvent
references: []
